### PR TITLE
DM-13567: Add tests to ap_pipe

### PR DESCRIPTION
**Pull request by mrawls**
Pair coded with @kfindeisen.

### CODE REVIEW

**Review by parejkoj — COMMENTED** [review]
How big is this package? Should it be in SQuaRE's list of "don't include this in binary distributions"?

**Comment by mrawls** [comment]
It is a 1.4 GB git-lfs repo, so probably yes. Where does this list live? I made PRs for `lsstsw` and `repos` as directed [here](https://developer.lsst.io/stack/adding-a-new-package.html). Is there an additional step needed so SQuaRE doesn't automatically try to add it to the binaries?

**Comment by kfindeisen** [comment]
I'm pretty sure he means the `manifest.remap` file in `lsstsw` (which we need to do regardless of the package size, because `eups` doesn't support Git LFS).

**Comment by parejkoj** [comment]
Did you get back an answer from SQuaRE about whether the manifest.remap is the only change necessary?

**Comment by mrawls** [comment]
Yes. Josh confirmed that eups products remapped to None in `lsst/lsstsw/etc/manifest.remap` don't have source packages generated.

**Pull request merged**
